### PR TITLE
feat: add the configure for declare copyright on posts

### PR DESCRIPTION
**Pull request by Jacksgong**
## Config on the `_config.yml`

```yml
# Declare license on posts
post_copyright:
  enable: true
  license: CC BY-NC-SA 3.0 CN
  license_url: http://creativecommons.org/licenses/by-nc-sa/3.0/cn/
```

## Result

image

### CODE REVIEW

**Comment by Jacksgong** [comment]
You can check out the effect from [my blog](https://blog.dreamtobe.cn).

**Comment by iissnan** [comment]
Thanks. :+1:

**Comment by ivan-nginx** [comment]
There is some questions about this pull.

In `_config.yml`:
1. Mb `post_copyright` in config need to replace into post block?
2. Why CN is default? EN for dafualt must be always.
3. `license_url` must be httpS.

In `post-copyright.swig`:
1. Why style is not use `note` tag style? There is no customization.
2. Why CN langauge again?
3. And where is customization of language again?

@Jacksgong i undestand what this is your own customization, but need to do faor all peoples and all languages, not only for CN.

@iissnan very easy merge.

**Comment by iissnan** [comment]
@ivan-nginx Good catches. I am working on the improvement to this pr right now.

**Comment by xiao-fang** [comment]
how can i disable some posts' copyrights but not all posts?

**Pull request merged**
