### PR TITLE
修正 leancloud 计数不能正常显示问题

### PR DESCRIPTION
**Pull request by Jefferlau**

### CODE REVIEW

**Comment by cduyzh** [comment]
最近我的阅读次数又出现问题了，按照你的修改提交了，不知道你的是否也有这种情况发生，麻烦告知下 @Jefferlau

**Comment by ivan-nginx** [comment]
@Jefferlau tnx!

**Comment by Jefferlau** [comment]
@cduyzh 我看了下我的博客，阅读次数是正常的

**Comment by ehlxr** [comment]
我的正常显示，按你的方式更新后反而不显示了，🤣

**Comment by ivan-nginx** [comment]
@ehlxr don't work after update u say?

**Comment by ehlxr** [comment]
@ivan-nginx yeah,so i rollback this part, and it work ok

**Comment by Will-Grindelwald** [comment]
@ivan-nginx @ehlxr 
me too. i rollback too.

**Comment by ivan-nginx** [comment]
@ehlxr @Will-Grindelwald let's say me: u do full rollback or just only part of it? That's update meaning:
1. Update of main script from `av-core-mini-0.6.1.js` to `av-core-mini-0.6.4.js`.
2. Add `AV.useAVCloudUS();` string.
So, i think in what part of thing there is trouble? May be just in second part or just in first part. Or on both? What do u think?

**Comment by ehlxr** [comment]
@ivan-nginx script version is not matter,i just remove `AV.useAVCloudUS();` and it work ok

**Comment by Will-Grindelwald** [comment]
@ivan-nginx I agree to @ehlxr

**Comment by Jefferlau** [comment]
我想到了一个问题，AV.useAVCloudUS(); 是因为我使用的 LeanCloud (美国)，非美国服务要将这句去掉。

**Comment by aixiu** [comment]
hexo-theme-next/layout/_third-party/analytics/lean-analytics.swig文件
```
  <script src="https://cdn1.lncld.net/static/js/av-core-mini-0.6.4.js"></script>
  <script>AV.initialize("{{theme.leancloud_visitors.app_id}}", "{{theme.leancloud_visitors.app_key}}");AV.useAVCloudUS();</script>
```
改为：
```
  <script src="https://cdn1.lncld.net/static/js/av-core-mini-0.6.4.js"></script>
  <script>AV.initialize("{{theme.leancloud_visitors.app_id}}", "{{theme.leancloud_visitors.app_key}}");</script>
```

**Comment by ivan-nginx** [comment]
Revert & update version: https://github.com/iissnan/hexo-theme-next/commit/23ee43ada2202a7c1c0362d86a6f8c32eac9fa1c

**Comment by myaooo** [comment]
It seems that the `id` of `$(".leancloud_visitors")` used for matching `url` will be different in `index` and `post/index`. In `layout/_macro/post.swig`, the `id` is rendered using `id="{{ url_for(post.path) }}`. So at `home` page, the `id` is normal. But at each `post` page. the `id` becomes null

**Pull request merged**
