### PR TITLE
Fix Click the image as hyperlink doesn't jump

### PR DESCRIPTION
**Pull request by WincerChan**
Users created a image as a hyperlink, when a user clicks on a
image, should jump to the url which the point of the hyperlink.

* Jump to the URL pointed to by the image

Previous problem:
when you click a image as a hyperlink:
screenshot_20170802_135647
Now you can jump normally

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@WincerChan can u please give live demo on this issue? As i remember, fancybox always work's fine.

**Comment by Acris** [comment]
@WincerChan Same to Ivan, can you give a demo site for this issue? thanks.

**Comment by WincerChan** [comment]
@ivan-nginx , @Acris  OK， that version is that I just cloned from master.
The problem is the image's class attribute.
peek 2017-08-07 12-19

**Comment by ivan-nginx** [comment]
@WincerChan this is not live demo. This is attached gif image. Live demo, please. Need to see src and other code.

**Comment by Acris** [comment]
@ivan-nginx  Here is: https://itswincer.com/life/

**Comment by ivan-nginx** [comment]
So? When i click on image, brower open me link on douban: https://movie.douban.com/subject/xxxxxxx/

**Comment by WincerChan** [comment]
@ivan-nginx my site has fixed not jump bug, the two version can not exist at the same time, I can revert to the previous version, now you can try click image in https://itswincer.com/life/.
before please open google debug tools as shown below picture `clear site data`(because my site enabled ServiceWorker, it would save cache file).
 **or simply change to another browser.**
screenshot_20170808_095023
NexT theme would add  `class="fancybox fancybox.image"` to all image, this causes click the picture hyperlink do not jump, you can inspect the image source code in https://itswincer.com/life/ page, change image class to `class="fancybox"`, it can jump normal.

**Comment by Acris** [comment]
I made this change on https://github.com/WincerChan/hexo-theme-next/commit/18dd7de6bb5e8fa16e5af49a59293759dbc6b6b9#diff-a85f8cc577970acb809c7250f9ae27e2, because by default, fancybox 2 uses the `href` or `data-fancybox-href` attribute of the matched elements to obtain the location of the content and to figure out content type you want to display. Fancybox 2 supports many types like 'image', 'inline', 'ajax', 'iframe', 'swf' and 'html'. In sometimes, we want to display an image but the image's url does not end with .jpg or .png, so fancybox can't figure out and can't display it, so I added the fancybox.image class to specify type directly.

**Comment by WincerChan** [comment]
@Acris  All right, I did not take this into account because the suffix of my site's picture is .jpg or .png.
but this does cause click on the picture hyperlink will not jump...

**Comment by Acris** [comment]
@ivan-nginx What do you think?

**Comment by ivan-nginx** [comment]
@WincerChan 
> NexT theme would add class="fancybox fancybox.image" to all image, this causes click the picture hyperlink do not jump

Yes, when a clear cache on your site and don't touch class name (stay it `fancybox fancybox.image`), image try load by fancybox, but not load it.
And this is not right.

> you can inspect the image source code in https://itswincer.com/life/ page, change image class to class="fancybox", it can jump normal.

Yes, when i remove `fancybox.image` from image in your site, click on image will jump to `href` link.
And this is right.

> but this does cause click on the picture hyperlink will not jump

I think image and hyperlink - this 2 diferrent things: hyperlink do jump at href path; image just appear picture in content, and if fancybox enabled in NexT config, image must just open full image wrapped with fancybox.
Another worlds:

* If we **click on image** - must show **fancybox** with this image
* If we **click on hyperlink** - must do jump at targeted **href**.

And question here: on what component we click? On image or on hyperlink?
And in [this sample](https://itswincer.com/life/), i see in source what `a href` is parent and `img src` is child. So, it it right what by clicking on `href` code do jump, not open fancybox, right?

I think need to add custom function, something about videogallery tag or anything else. Like addition option behind `fancybox: true` something like `fancybox.wrap_href` to add or remove `fancybox.image` class and/or use `data-fancybox-href`. Or, need to reconstruct `fancybox.image` code.

@Acris can u give commit on your changes with
> so I added the fancybox.image class to specify type directly

?

**Comment by WincerChan** [comment]
@ivan-nginx ok, my `.md` use **HTML syntax** to describe image hyperlinks, like this:
```html
<a href="https://movie.douban.com/subject/25986180/" title="부산행&#10;&#10;釜山行 / 尸速列车(台) ">
<img src="https://img1.doubanio.com/view/movie_poster_cover/lpst/public/p2360940399.jpg">
</a>
```
and It also can described in markdown syntax:
```markdown
[![](https://img1.doubanio.com/view/movie_poster_cover/lpst/public/p2360940399.jpg)](https://movie.douban.com/subject/25986180/ "부산행&#10;&#10;釜山行 / 尸速列车(台)")
```
**but** when I convert markdown to html page, the Line breaks `&#10;` of title can't convert (because the `&` in markdown is special ), so I use HTML syntax.

**Comment by ivan-nginx** [comment]
> because the & in markdown is special ), so I use HTML syntax.
BTW, u can try to use escape characters (\&#10).
@WincerChan ok, i see what `img` tag placed inside `a` tag. So, by default it must to do jump, right?
And what u want? U want to jump or to show image in fancybox?
And second question: if u want to show image, how u do jump to see movie?

**Comment by WincerChan** [comment]
@ivan-nginx yes, whatever something(*text or image*) as hyperlink, when click it, by default it should do jump.
If I set a image as hyperlink (`<a>` tag contains `` tag), I want to jump.
Else I just want show a movie image (*when someone click image, show in fancybox*), then I should set a text (like movie title) hyperlink pointed the url outside of `a` tag,like(html):
```html
<img src="https://img1.doubanio.com/view/movie_poster_cover/lpst/public/p2360940399.jpg">
<a href="https://movie.douban.com/subject/25986180/">부산행&#10;&#10;釜山行 / 尸速列车(台) </a>
```
I think if something is used as a hyperlink, then the most important thing (*or its highest priority attribute*) is **pointed the URL**.

**Comment by geekrainy** [comment]
Refer to my improvement. https://github.com/geekrainy/hexo-theme-next/commit/c1d1a5952ecf3d8843dc2bc0f837d7ad61987017 https://github.com/geekrainy/hexo-theme-next/commit/8555cd76b52be8712bdd324a2c803faf50402d33

And live demo: https://rainylog.com/douban/

**Comment by ivan-nginx** [comment]
@geekrainy pull?

**Comment by geekrainy** [comment]
@WincerChan I think we can consider optimizing the merge pull the pull request, suitable for more general situation.

**Comment by stevenjoezhang** [comment]
Added in https://github.com/theme-next/hexo-theme-next/pull/468

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, please, [create pull in NexT v6.x / v7x repo](https://github.com/theme-next/hexo-theme-next/pulls).
There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.

**Pull request closed without merging**
