### PR TITLE
enable motion of nav bar

### PR DESCRIPTION
**Pull request by flashlab**
A bug exists while switch between mobile and desktop view.

### CODE REVIEW

**Comment by flashlab** [comment]
Can I acess your blog html source? @houndci-bot

**Comment by iissnan** [comment]
@flashlab HoundCi is a code style checker. It will check all pull requests and comment if there is something incorrect. For this case, you changed `sidebarToggleLines` to a global variable and does not declare it in JSHint configuration file, so it consider this is an issue. We may need to store this variable into somewhere

**Comment by flashlab** [comment]
:confused: I'm quite not familiar with this. Maybe you have got the idea, so I'll close it for now. Hope you can consider to apply this function :smile:

**Comment by flashlab** [comment]
Any suggestion on this modification? @iissnan

**Comment by iissnan** [comment]
You can put `sidebarToggleLines` under `NexT` namespace then use it in motion.js and bootstrap.js.

By doing that, HoundCI will not complain.

**Comment by iissnan** [comment]
By the way, I am thinking about dropping the support for IE9 so that we can leverage more CSS animation features.

For this case, `sidebarToggleLines` would be replaced with CSS.

**Comment by flashlab** [comment]
Agree. Since taking care of visual effect though css will be more resonable. :+1:

**Pull request closed without merging**
