### PR TITLE
Add Hypercomments system.

### PR DESCRIPTION
**Pull request by ivan-nginx**
Add support for [Hypercomments](https://www.hypercomments.com/) system instead of [Disqus](https://disqus.com/).

### Hypercomments support
- Anonymous comments.
- Inline comments like Duoshuo (u can select any text and make comment for this text).
- Share selected text with title in social (Facebook, Twitter, VK).
- Copy quotes (when u copy selected text from site it will appear at quotes tab in comments).
- Stereocommets (mode with moderators’ avatars/mode with company logo)
- Categories (will help users to add a comment to the appropriate section e.g.'Сriticism', 'Reference', 'Request' etc.).
- Emoji in comments. :relieved:
- Real-time online post views.
- Real-time moderation.

U can see and test live demo of hypercomments [here](https://almostover.ru/2016-10/add-hypercomments-to-hexo-theme-next/).

### CODE REVIEW

**Comment by iissnan** [comment]
Thanks. :+1:

**Comment by Maples7** [comment]
赞，现在多说已经太不靠谱了。

**Comment by AlynxZhou** [comment]
这个跟disqus比起来怎么样呢？希望比较稳定

**Comment by eeemt** [comment]
试了试，好用

**Comment by Keldos-Li** [comment]
能否支持简体中文？为何显示的是繁体中文。。
can it support Chinese Simplified? i don't understand why it use Chinese Simplified ....and i can't find where set.

**Comment by ivan-nginx** [comment]
@Keldos-Li this is 3rd party service. All langs loading from HC server, so, need to ask it on they site, not here.

**Comment by tcsds** [comment]
这个好用，但是，要是有简体中文就更好了，真是忧伤~~

**Comment by ivan-nginx** [comment]
> can it support Chinese Simplified? i don't understand why it uses Chinese Simplified ....and i can't find where set.
I ask about Chinese language to HC maintainers and he's said Chinese language is supported. As i understand, `Chinese` and `Chinese Simplified` - are not the same and they not support `Chinese Simplified`, but support `Chinese` right? I can talk him again about this. Also, if anybody can help with translate HC into `Chinese Simplified`, we may give this translate to him.

**Comment by Keldos-Li** [comment]
Thanks

**Pull request merged**
