### PR TITLE
Add bootstrap label alert

### PR DESCRIPTION
**Pull request by liuzhenrain**
# Label style
> usage: {% label class %} content {% endlabel %}

class : 
> default, primary, success, info, warning, danger

files:
> next\source\css\_common\components\tags\tags.styl
> next\scripts\tags\label.js

站点配置主要在 {% label primary %} 博客根目录 {% endlabel %}的\`_config.yml\`文件中配置

Result:
image

# Alert
> usage: {% alert [tips] [class] %} content {% endalert %}
> if tips is null then will replace with default string. e.g. *Warning Message (class = warning)*
> content can use Markdow syntax **but except (\``` message \```)**

class : 
> success, info, warning, danger
> class default is success

files:
> next\source\css\_common\components\tags\alert.styl
> next\scripts\tags\alert.js

{% alert "警告提示" warning %}
    \`这是一个警告提示\`
    \# Hello Bootstarp
{% endalert %}

Result:
image

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@liuzhenrain alert is duplicate of note tag?

**Comment by liuzhenrain** [comment]
@ivan-nginx maybe is true with duplicate note tag ,but is note same display,and note tag has some error.so I add the alert tag.
Alert like this:


Note like this:

**Comment by ivan-nginx** [comment]
> and note tag has some error

Errors like what?

I know how looks note tag, i made it. For example, at [this link](https://almostover.ru/2016-01/hexo-theme-next-test/) u can see same note tag, but with modify css.

And, yes, i see how look your note (alert) tag, but this is css style only. Any other functionality is on same level, instead of original note.js have 11 strings of code and your alert.js have 45 strings of code.

**Comment by liuzhenrain** [comment]
@ivan-nginx 
Error like this:


If i delete the second note tag ,it will be right to generate.
Like this:
image

**Comment by ivan-nginx** [comment]
@liuzhenrain may i see source code with this error? Mb u not right use this tag.

**Comment by liuzhenrain** [comment]
@ivan-nginx 
[2017-06-02-note-error.txt](https://github.com/iissnan/hexo-theme-next/files/1045605/2017-06-02-note-error.txt)

**Comment by ivan-nginx** [comment]
@liuzhenrain ok, i see what u use {% note warning %}string{% endnote %}, right?
Can u please use note tag with instructions?
***
No need to write this in 1 line, like that:
```
{% note danger %}note danger, note danger, note danger{% endnote %}
```
or like that:
```
{% note danger %}note danger
note danger
note danger{% endnote %}
```
Need to write it like u may see in note documentation link (#1160), like this:
```
{% note danger %}
note danger, note danger, note danger
note danger, note danger, note danger
note danger, note danger, note danger
{% endnote %}
```

**Comment by ivan-nginx** [comment]
@liuzhenrain let's do it again and catch this error: need clean source code in English language, without any other addition styles/letters/etc.
If error will, i'll try to fix it and/or think about alert tag.
If error not will, need just to add css style to present note tag.
For now i don't see any errors with note tag.

**Comment by liuzhenrain** [comment]
I Changed two tag like :
```
{% note danger %}
note danger, note danger, note danger
note danger, note danger, note danger
note danger, note danger, note danger
{% endnote %}
```
**IS OK**
and can be only use like that... if you have more then one note tag..
Thank you..

**Comment by ivan-nginx** [comment]
@liuzhenrain you are welcome. Need to use by instructions all tags and/or modules if want no errors.
But i will make css style on note tag and label tag style too. Thank's for pull, it's real help me.

**Comment by liuzhenrain** [comment]
@ivan-nginx  if you can modify the Chinese doc with [Bootstrap Callout](http://theme-next.iissnan.com/tag-plugins.html#bootstrap-callout).
Please modify it..

**Comment by ivan-nginx** [comment]
@liuzhenrain this can modify @iissnan and i don't know Chinese. And now i see what docs is not right.

P.S. Close #1674 if solved.

**Comment by liuzhenrain** [comment]
@ivan-nginx Need me to close this PR?

**Comment by ivan-nginx** [comment]
@liuzhenrain no no, this PR no need to close for now. I will close it when i finish with this tags and styles. Thx.

**Comment by liuzhenrain** [comment]
@ivan-nginx  
OK
It's time to sleep 
....bye....

**Comment by ivan-nginx** [comment]
@liuzhenrain add modern note style in #1697. Some later i'll add label style too.

**Comment by ivan-nginx** [comment]
Label tag was added in #1697 **PART 8**.

@liuzhenrain thank's for pull, it really help for me!

**Pull request closed without merging**
