### PR TITLE
Feature: Add Gitment Support

### PR DESCRIPTION
**Pull request by LEAFERx**
增加gitment集成
并实现了按钮延迟加载
如@ehlxr在[Issue#1604](https://github.com/iissnan/hexo-theme-next/issues/1604)所述部分功能

### CODE REVIEW

**Comment by AlynxZhou** [comment]
感觉这是个deadly need啊……为啥一直不merge呢……比第三方舒服多啦……

**Comment by ivan-nginx** [comment]
@AlynxZhou need to test it totally before merge. And i think need to make some additions to this pull. Need some time or any beta-testers with live-demo examples.

**Comment by AlynxZhou** [comment]
@ivan-nginx seems few people test PRs… and seems NexT now contains so many functions and some are outdated… And maybe split three scheme into three themes will be better to maintain?

**Comment by dreampiggy** [comment]
@ivan-nginx So...How soon can this PR merged? Or is there anything important to discuss ? I've test it for nearly one month(through I'm not using the latest Hexo and just merge upstream as need).

**Comment by ivan-nginx** [comment]
@dreampiggy i need to finish my #1697 PR for start working on this PR. I'm working and i can't to do fast anything alone. If it's worked fine, it's good and it will be merget, be sure. But need some time for this.

What about discuss? Ok, there is one thing in Gitment system what i saw about month ago. Look at [this](https://github.com/imsun/gitment/pull/25) pull from **30 MAY 2017** and say me: why @imsun don't want to merge this pull?
There are some cool features by @aimingoo comment:

* No client_secret
* Force redirect protocol to support HTTPS/HTTP Github pages site
*  protected token
* language translator for default/other theme, a simple method

For example, i don't wan't to use any client_secret from my Github just for use comments system, and this pull already add alternative:
```
# This is used for now
this.state.user.isLoggingIn = true
http.post('https://gh-oauth.imsun.net', {
    code,
    client_id,
    client_secret,
  }, '')
  .then(data => {
    this.accessToken = data.access_token
    this.update()
  })

# This additions in not merget pull:
this.state.user.isLoggingIn = true
var login = !proxy_gateway
  ? http.post('https://gh-oauth.imsun.net', {code, client_id, client_secret}, '')
  : http.post('/login/oauth/access_token', `code=${code}&client_id=${client_id}`, proxy_gateway);
login.then(data => {
  this.accessToken = data.access_token
  this.update()
})
```
As u can see, for now (without not merget pull) access token do post query on `https://gh-oauth.imsun.net` site and this is very interesting from point of view by `log files`.

Another words: i don't want to do any post queries with **access tokens** from my **Github accont** with **full access** to any **3rd party site (https://gh-oauth.imsun.net)** via **http protocol**.

P.S. If u so want this function with this pull, u may ask @imsun - why he's not want to merge [this](https://github.com/imsun/gitment/pull/25) pull from 30 may?

**Comment by dreampiggy** [comment]
@ivan-nginx OK, This PR(https://github.com/imsun/gitment/pull/25) for Gitment is really great(Especially for that access tokens proxy and HTTPS support). I will try to test that and push @imsum to review.

**Comment by ivan-nginx** [comment]
@dreampiggy yep. And that's why i'm waiting...

**Comment by aixiu** [comment]
It's not cool to press the button to delay loading. Can you make default settings?

**Comment by Leo-Mu** [comment]
这么长时间了！
什么时候才能通过啊？急需啊！
Deadly need! I want it!
@iissnan @ivan-nginx @geekrainy @flashlab @Acris @voiddog @Lanseria @Jefferlau @Jacksgong @guahsu @Asing1001 @shenzekun @tinpont @dolphinlin @uchuhimo

**Comment by muzhi1991** [comment]
冲突还没有合并？

**Comment by aimingoo** [comment]
有什么我能做的么？

**Comment by ivan-nginx** [comment]
@aimingoo u help if u try to adapt gitm**i**nt to this theme.

**Comment by VeiZhang** [comment]
Waiting for success!

**Comment by aimingoo** [comment]
@ivan-nginx 

这两天趁着过节把这个theme的代码以及这个pull request的changes看了看。我倒觉得这个request的实现没什么问题，我在想是等这个merge之后再基于这个update提一个gitmint的pull呢，还是现在就独立地提一个。有点拿不定主意，但已经在开始改代码了。

另外，我注意到在这个theme中有三处可以集成comments的地方。但我仔细读了一下github issues api的文档，theme中有一处显示count的地方是无法实现的（就是index/list页上的comments count），因为github issues中取这个count值的代价特别高，强行去做的话，这个index/list页的性能会特别差。

综上，gitmint可能会比现在这个commit多出三个特性：

* support no client_secret
* support language translator
* support comments count in single post page

**Comment by ivan-nginx** [comment]
@aimingoo dude, please, write in English. I don't understand Chinese and gTranslate can't to translate long messages cleanly.

@LEAFERx can u please to refactor this and try to adaptat [Gitm**i**nt](https://github.com/aimingoo/gitmint) instad of Gitm**e**nt?

**Comment by LEAFERx** [comment]
@aimingoo im not really farmilar with gitmint and i have another pr to work on. so i think its a good idea that you do this job.
我建议你Fork我的Fork的master分支然后改成gitmint 或者独立提交一个pr也行

**Comment by aimingoo** [comment]
@LEAFERx good! I'll try this now!

@ivan-nginx I cant write long english messages because my english is poor... but i'll try the new work base LEAFERx's idea~

**Comment by ivan-nginx** [comment]
@aimingoo my English is poor to, i'm not was in US or EU, но я же не пишу на Русском, ибо кто меня поймёт без переводчика? Just write with simple words what all will understand, it's easy.

Ok, i'll be glad (not only i, of course) if your guys integrate Gitm**i**nt into NexT. I just don't want to make possible vulnerability for users with use Gitm**e**nt (i talked about it above), so, only your Gitmint fork may give almost full the freedom of choice.

**Comment by aimingoo** [comment]
@ivan-nginx @LEAFERx 

DONE. #1919

**Pull request closed without merging**
