### PR TITLE
add subtitle to home index

### PR DESCRIPTION
**Pull request by zhaiqianfeng**
add subtitle to home index

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@zhaiqianfeng need add config switch for this option.

**Comment by zhaiqianfeng** [comment]
ok. I have improved.

**Comment by zhaiqianfeng** [comment]
@ivan-nginx ok. I have improved.

**Comment by ivan-nginx** [comment]
@zhaiqianfeng ok. there is some errors in your code.

If we open src, we will see:
```
  <title> 
   Hexo Test 
   
     - Subtitile 
   
</title>
```
And this is wrong and bad for seo.

But this code will be nice, without excess spaces:
```
{% block title %}{{ config.title }}{% if theme.index_withsubtitle and config.subtitle %} - {{config.subtitle }}{% endif %}{% endblock %}
```

P.S. REM: also, need to fix all extra spaces on other subpages.
image

**Comment by zhaiqianfeng** [comment]
Thank you  @ivan-nginx

**Pull request merged**
