### PR TITLE
Fixes in CSS styles of code blocks.

### PR DESCRIPTION
**Pull request by ivan-nginx**
1. Add support diff highlight style (#1079).
2. Add border radius to code blocks.
3. Tomorrow theme on single code blocks.

[Demo](https://almostover.ru/2016-01/hexo-next-diff-highlight-test/).

---
## Tomorrow Normal
image
---
## Tomorrow Night
image
---
## Tomorrow Night blue
image

### CODE REVIEW

**Comment by iissnan** [comment]
It seems the `highlight.styl` has confilicts with https://github.com/iissnan/hexo-theme-next/pull/1079. Could you please help to resolve those conflicts on this PR?

**Comment by ivan-nginx** [comment]
@iissnan this is conflict?
```
+  word-wrap: break-all;
 -  color: $code-foreground;		 +  color: $highlight-foreground;
 -  background: $code-background;		 +  background: $highlight-background;
```

**Comment by ivan-nginx** [comment]
https://github.com/ivan-nginx/hexo-theme-next/commit/f99be24bb78c9c1c42439747979c631042ea726a

1. Remove border-radius (always show horizontal scrollbar on mobile devices).
2. Replace word-break with word-wrap, because don't break whole word on letters.
    https://webref.ru/css/word-break
    https://webref.ru/css/word-wrap

**Comment by iissnan** [comment]
Merged. Thanks :+1:

**Pull request merged**
