### PR TITLE
feature: add loading animation when search data is loading

### PR DESCRIPTION
**Pull request by uchuhimo**
When clicking search button first time, it will spend a long time loading search data if `search.xml` is large (usually 5-10 seconds), without any response. I add a loading animation to indicate the loading process. Demo:

fireshot capture 16 - uchuhimo s note - http___localhost_4000_

### CODE REVIEW

**Comment by ivan-nginx** [comment]
GJ! I'll test it soon. Wait for response.

**Comment by ivan-nginx** [comment]
@uchuhimo loading work perfectly. But, it is really need to add `*.svg` picture, if we already have fontawesome icons? Can u check [this page](http://fontawesome.io/examples/), there are animation icons and may be just use them instead of svg? If it's possible, of course.

**Comment by uchuhimo** [comment]
@ivan-nginx Thank you for reminding me, I will try and update the pull request if it's possible.

**Comment by ivan-nginx** [comment]
@uchuhimo firstly, need to test and try it. If FA will better, need to use it, i think.

**Comment by uchuhimo** [comment]
@ivan-nginx It works. Demo:

fireshot capture 16 - uchuhimo s note - http___localhost_4000_

The appearance is similar. We can reduce the svg picture if we use animation icon.

**Comment by ivan-nginx** [comment]
@uchuhimo ok, do how it will be better. ;)

**Comment by uchuhimo** [comment]
@ivan-nginx I have updated this pull request, check it please

**Comment by ivan-nginx** [comment]
@uchuhimo yeah, it's work fine and no need svg icon. Well done and thanks!

**Pull request merged**
