### PR TITLE
fix #1943 fix the bug of gitment

### LINKED ISSUE #1943: Gitment 配置问题
https://github.com/imsun/gitment/issues/46
这个issues 里提到带参数的 URL 和 不带参数的 URL 会被当成不同的网页处理。需要将

id: document.location.href

改成 id:window.location.pathname

### PR DESCRIPTION
**Pull request by leviding**
fix the bug of gitment, change `document.location.href` to `document.location.pathname`

## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/iissnan/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes have been added (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [ ] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number(s): N/A

## What is the new behavior?
Description about this pull, in several words...

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [ ] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
In #1943 instead of `document` — `window`. Are u test it?

**Comment by leviding** [comment]
@ivan-nginx I haven't tested it yet, just modify the file as what @icearith say. But I see somebody have tested it in https://github.com/imsun/gitment/issues/46.

**Comment by icearith** [comment]
This modification is cloud only be a hot-fix level solution for this issue, because this is a problem related to the design of Gitment. Some guys mentioned that Gitment should use `permalink ` in `hexo` to identify the unique post. 

Although this solution is not 100% reliable, it could also improve the reliability of this plugin, because many links pass arguments to URLs, for example, http://a.com?from=baidu this is regarded as a different post from http://a.com.

This commit could solve this issue from URL level, the issues mentioned in https://github.com/imsun/gitment/issues/46 should be label as a **upstream issue**, which should be solved in upstream repository.

**Comment by ivan-nginx** [comment]
So? What's the difference between `document` and `window`?
Please, not need to add code into master if you not test it in realtime. NexT already have thousand bugs.

**Comment by leviding** [comment]
It's ok to close this PR, and wait somebody or me have better solution, then fix this bug.

**Comment by icearith** [comment]
@ivan-nginx I mean,  the point is that `href` is definitely wrong, `pathname` should be used.

**Comment by ivan-nginx** [comment]
It's ok to do 100% bugfix PR's. And it's ok to test all changes before make PR into master branch.

Guys, let me explain there something. There is 3 ways:
1. `document.location.href`
2. `document.location.pathname`
3. `window.location.pathname`

What's the right answer? :smiley: 

P.S. I don't talk about «Oh no, u not tested it, this is wrong bugfix, etc.». A just talking about right way to fix.

**Comment by ivan-nginx** [comment]
I changed `document.location.pathname` to `window.location.pathname`.

**Pull request merged**
