### PR TITLE
Feature: Added Gitalk support.

### PR DESCRIPTION
**Pull request by AlynxZhou**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [X] The commit message follows [our guidelines](https://github.com/iissnan/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [X] Tests for the changes have been added (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [X] Pisces | Gemini have been tested.
- [ ] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [X] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

A similiar pull request has been created but due to some reasons didn't pass.

Issue Number(s): N/A

## What is the new behavior?
Description about this pull, in several words...

screenshot from 2017-12-17 11-08-18
screenshot from 2017-12-17 11-08-28

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [X] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@AlynxZhou as i see, this looks like on Github? But this is save comments like Gitment, right? If yes, i think need to add config on this right into Gitmint/Gitment for reverse compatibility.

**Comment by AlynxZhou** [comment]
In fact this is a different comment system, just works like gitment, but I
am afraid it cannot use config in gitment because they are diffierent
projects, they have diffierent code and people use one won't use another, I
think, because seems no one tested can one read another's issue as its
comments, just let them two choice.

**Comment by ivan-nginx** [comment]
And in fact just css and js styles have different, right? So, i think about migrate this styles to Gitmint/Gitment and peoples can choice what style they want: standart Gitment style, or this, modernize style. That's what i'm talking about.

For now this have modern style but use standart imsun's Gitment gateway, and i don't aprecciate it (see my comment about this [here](https://github.com/iissnan/hexo-theme-next/pull/1634#issuecomment-313596649)).

I inderstand what it's pretty beautifull Gitment patch, but what users will do if they GitHUB account's will be breaking down? Who will answer for this doings if thousand peoples wil talk something about: i installed NexT theme and turn on coll comments system, but my Github accound was stolen then. This is just example, think about it.

Need to do hardfork of this styles, this will be best decision.

**Comment by AlynxZhou** [comment]
OK, I am back to my dorm and have read a lot words about it because I know little, firstly I add gitalk just because original gitment is inactive for a long time, and don't know things about gitmint and client secret, finally I think I understand what you mean.
You mean that using client secret like gitalk/gitment is insecure and NexT uses a fork called gitmint which allows user to build a own proxy to hide client secret. So we need something like mint to work with gitalk, that's what you mean, right? However this seems beyond my ability, I may ask gitalk author to add, or try to fork it myself but not now because I need to learn how to make it and I need to pass my final term exam first. ;-)
Please tell me if I misunderstood your words.

**Comment by ivan-nginx** [comment]
That's right.

**Comment by zjuturtle** [comment]
@ivan-nginx @AlynxZhou I don't think you should worry about github account stolen if you use gitalk. Because gitalk can use Github App. The home page on gitalk lead you to a OAuth app apply(Which is not needed). Use Github App to control access will be pretty nice (only issue read and write is allowed). I don't think hide Github App secret is a must.

**Comment by zjuturtle** [comment]
Shit I made a mistake. Github App won't work. My bad.

**Comment by SharryXu** [comment]
Hi @ivan-nginx , will you merge this pull request?

**Comment by GavinBrook** [comment]
ok

**Comment by xiaotiandi** [comment]
股份公司

**Comment by ivan-nginx** [comment]
Already added in NexT 6 here: https://github.com/theme-next/hexo-theme-next/pull/464

***

NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, please, [create pull in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/pulls).
There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.

**Pull request closed without merging**
