### PR TITLE
Add comment LiveRe

### PR DESCRIPTION
**Pull request by asmoker**
for issue #1396

add LiveRe comments for next themes
添加来必力评论支持

for more detail, please read my blog.
更多细节请访问我的博客 [https://blog.smoker.cc/web/add-comments-livere-for-hexo-theme-next.html](https://blog.smoker.cc/web/add-comments-livere-for-hexo-theme-next.html)

### CODE REVIEW

**Comment by zxiang179** [comment]
驱蚊器

**Comment by cpm828** [comment]
手机端显示有个bug，ios10微信和safari都有问题，其他未知，查看：http://ost24ftl4.bkt.clouddn.com/IMG_1146.PNG

**Comment by sli1989** [comment]
Return address of livere is 404.html? Does anyone have this problem?

**Comment by CJCSDN** [comment]
最新版的next加入来必力，分类和归档都有了，如何只加载文章页里面而不是全部页面都有加？

**Comment by sli1989** [comment]
@CJCSDN add `comments: true` in front-matter.

**Pull request merged**
