### PR TITLE
Fix Mist's classname 'footer-inner' text-align left to center

### PR DESCRIPTION
**Pull request by dskin**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/iissnan/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

When i use schemes  of Mist,i found that the footer didn't center but other schemes are good,then i found the '/sourse/css/_schemes/Mist/index.styl' had override '/sourse/css/_common/components/footer/footer.styl',the first one's text-align do something wrong,so i change it.
Issue Number(s): N/A

## What is the new behavior?
it works

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
Wich schemes are good and wht's the trouble with Mist? Need screens and more comments.

**Comment by dskin** [comment]
**I mean the text in the footer is not centered in Mist,like this**

mist-footernotcenter

*********
**but Muse,Pisces and Gemini is ok,like this**

muse-center
pisces-center
gemini-center
*********

Maybe  the `text-align:left` is a feature?:blush:

**Comment by ivan-nginx** [comment]
I think this feature, not a bug. But u can change it without additional modifications in main branch.
All of u need just add in `source/css/_custom/custom.styl` your CSS changes:
```css
.footer-inner {
  text-align: center;
}
```
All styles added here will rewrite any standart styles. And u can later syncronize your main code  without merge breaking.

**Comment by dskin** [comment]
get it,thanks！

**Pull request closed without merging**
