### PR TITLE
FIX: Footer in Gemini and Pisces always keep in bottom.

### PR DESCRIPTION
**Pull request by AlynxZhou**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [X] The commit message follows [our guidelines](https://github.com/iissnan/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [X] Tests for the changes have been added (for bug fixes / features).
- [X] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [X] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number(s): #1818 

## What is the new behavior?
Footer in Gemini and Pisces always keep in bottom.

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

## Does this PR introduce a breaking change?
- [ ] Yes.
- [X] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
Can u show here Github pages code? Your code in `footer.swig`.

**Comment by AlynxZhou** [comment]
```html
Hosted by <a href="https://pages.github.com" style="font-weight: bold">GitHub Pages</a>
<br>
Hosted by <a href="https://pages.coding.me" style="font-weight: bold">Coding Pages</a>
```

@ivan-nginx In China we have a github-like website called coding, some people like me use it as a mirror in China, but it ask user to add those lines "Hosted by Coding Pages" in pages, I added them in footer, and then I need to enlarge the footer height to contain them properly. However I think this has no influence to NexT, not all people need this.

**Comment by ivan-nginx** [comment]
@AlynxZhou there is new option `custom_text` in #1886.

**Comment by AlynxZhou** [comment]
@ivan-nginx That's really cool! Thanks!

**Pull request closed without merging**
