### PR TITLE
json search engine support

### PR DESCRIPTION
**Pull request by flashlab**
add json option to local search.

TODO:
- search with tag and catalog
- doc update

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@flashlab can u please give some comments and examples how to use it?

**Comment by flashlab** [comment]
In the local search field of config file, 'search.xml' will end with xml database generated while 'search.json' comes with the json. @ivan-nginx

**Comment by ivan-nginx** [comment]
@flashlab and? How to use `json` in search? Need something like documentation to test it for merge.

**Comment by flashlab** [comment]
Update generator plugin to the latest version. @ivan-nginx

**Comment by ivan-nginx** [comment]
@flashlab there are 2 generators for search: `hexo-generator-search` and `hexo-generator-searchdb`. Both support `json`?

**Comment by flashlab** [comment]
yes. but only the latter one is compatible with Next.

**Comment by ivan-nginx** [comment]
@flashlab need to update `hexo-generator-search` to latest version, which is automatically support `json` objects, right?

> but only the latter one is compatible with Next
So, `hexo-generator-searchdb` for now is not compatible with Next, right?

**Comment by flashlab** [comment]
No, I mean hexo-genrator-searchdb is compatible. the latest vesion(1.0.5) support json.

**Comment by ivan-nginx** [comment]
@flashlab ok, lets repeat it:

1. This pull is support compatible with `json` objects for Next theme.
2. To use this `json` compatible, need to setup [`hexo-generator-search-db`](https://github.com/flashlab/hexo-generator-search) **instead** of original [`hexo-generator-search`](https://github.com/PaicHyperionDev/hexo-generator-search).

It is right?

***

P.S. Also, can u, please, rename path from
`https://github.com/flashlab/hexo-generator-search` to
`https://github.com/flashlab/hexo-generator-searchdb` 
to see in google what it's modification and not just original fork?

**Comment by flashlab** [comment]
@ivan-nginx it's forked because it was modified from the original one to work better with Next. No need to initiate a new path I think.

**Comment by ivan-nginx** [comment]
@flashlab ok, what about last question?
> It is right?

**Comment by flashlab** [comment]
Absolutely right. And we may continue this conversation in chatter;)

**Comment by ivan-nginx** [comment]
> And we may continue this conversation in gitter

Ok, check gitter, there is 1 bug.

**Comment by ivan-nginx** [comment]
There is some instructions for use [`hexo-generator-search-db`](https://github.com/flashlab/hexo-generator-search) with this pull request. Check your NodeJS and NPM versions.

- NodeJS > 4.2 & NPM > 3: just follow [this instructions](https://github.com/iissnan/hexo-theme-next/pull/1635#issuecomment-298132570).
- NodeJS < 4.2 & NPM < 3: need to install separated patch with `npm install hexo-generator-searchdb@0.0.7` command. You may see this patch in `[old-nodejs](https://github.com/flashlab/hexo-generator-search/tree/old-nodejs)` branch and follow [same instructions](https://github.com/iissnan/hexo-theme-next/pull/1635#issuecomment-298132570).

**Pull request merged**
