### PR TITLE
Fix Issues 1134

### PR DESCRIPTION
**Pull request by kirito269**
Fix Google Analytics can’t use

### CODE REVIEW

**Comment by ivan-nginx** [comment]
Google analytics work's fine on both HTTP and HTTPS protocols without scheme.

**Comment by kirito269** [comment]
I think it's essential to add HTTPS as it's certainly the future  and tendency.

**Comment by ivan-nginx** [comment]
@kirito269 google want HTTPS only on sites who's need this HTTPS (shops, user passes, etc.).
On static blogs HTTPS may be, but don't need by google instantly.

I see my HTTP site and GA work fine. But, there is some error and i will rechecked it. But i think what GA script no need scheme by this fix.

**Comment by iissnan** [comment]
It is reasonable to add `https` scheme to the uri of the tracking script, since Google now only serve it over https. Actually there would be a `307` redirection if using `http` scheme,  but I didn't figure out why it does not work.

**Pull request merged**
