### PR TITLE
Fix canvas-ribbon error.

### PR DESCRIPTION
**Pull request by geekrainy**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [ ] The commit message follows [our guidelines](https://github.com/iissnan/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes have been added (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

If use plugin [hexo-all-minifier](https://github.com/chenzhutian/hexo-all-minifier), will report an error:

```
ERROR Asset render failed: lib/canvas-ribbon/canvas-ribbon.js
```

So I upgrade this script file from https://github.com/zproo/canvas-ribbon.

Issue Number(s): N/A

## What is the new behavior?

Now error is not appear.

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
Thanks!

**Comment by ivan-nginx** [comment]
@geekrainy but i see bug in your blog: https://rainylog.com/tags/ — sidebar get wrong position.

It is normal to have so many errors in this script?

**Comment by geekrainy** [comment]
@ivan-nginx I have noticed this problem, it is not caused by this script. This is my own branch of the problem, I will fix it.

**Comment by ivan-nginx** [comment]
@geekrainy ok, it's somewhere in scripts with sidebar alignment. See `utils.js`, `pisces.js`, `post-details.js`.

**Comment by ivan-nginx** [comment]
@geekrainy can u comment #1935 issue?

**Pull request merged**
