### PR TITLE
fix ribbon cause scroll not working

### PR DESCRIPTION
**Pull request by dolphinlin**
the code cause an exception.
```js
  document.addEventListener("touchmove", function(e) {
    e.preventDefault()
  });
```

see that > [JS MDN](https://developer.mozilla.org/en-US/docs/Web/Events/touchmove)

### CODE REVIEW

**Comment by ivan-nginx** [comment]
This is fix? All worked fine?

**Comment by dolphinlin** [comment]
yeap!
remove the code from there, it works

**Comment by ivan-nginx** [comment]
Ok, well done! And thanks!

**Comment by dolphinlin** [comment]
i improved the performance.
i think the code that avoid redrawing background when touch screen to click or move.
click -> do to.
move -> don't to do.

so i add some judgment for improving performance

i need to PR?

**Pull request merged**
