### PR TITLE
Some small fixes.

### PR DESCRIPTION
**Pull request by ivan-nginx**
Fixes for Muse and Mist schemes for #1438.

### CODE REVIEW

**Comment by iissnan** [comment]
Thanks. :+1:

**Comment by Acris** [comment]
@ivan-nginx There still have some small problems.... such as the two square's width are not same... QAQ

**Comment by ivan-nginx** [comment]
image
image
@Acris  where?

**Comment by Acris** [comment]
@ivan-nginx 
There are 0.35px difference, see picture below:

sidebar-toggle:


back-to-top:

**Comment by ivan-nginx** [comment]
@Acris ok, it's done. 24x24px both blocks, check it.

**Pull request merged**
