### PR TITLE
Fixes bugs

### PR DESCRIPTION
**Pull request by geekrainy**
Commit a8cdb8783bb9054c6bf2648d52669309b0c30283: 
Before:

After:

Commit 7f66f8d85c4b3c55f8f6183af7bcfe501c74e4f8:
Before:

After:

### CODE REVIEW

**Comment by Ethan-Zhang** [comment]
Commit @7f66f8d 没有看出区别啊

**Comment by geekrainy** [comment]
@Ethan-Zhang 链接的间距和 Muse, Pisces 保持一致。

**Comment by Ethan-Zhang** [comment]
+1

移动端chrome测试header-inner和foot-inner，横屏竖屏都能占满屏，显示正常了，赞

**Comment by iissnan** [comment]
:+1:  Thanks!

**Pull request merged**
