### PR TITLE
Add support for tencent analytics.

### PR DESCRIPTION
**Pull request by Cissoid**
Google analytics 虽好，在大陆总有一层墙的问题。
百度统计虽然很多人用，但相信总有越来越多的人因为百度的持续性作死而放弃使用其全部产品。
所以希望加上对腾讯统计的支持，another choice :)

### CODE REVIEW

**Comment by iissnan** [comment]
Thanks. :+1:

**Comment by tc9011** [comment]
您好，请问一下为什么用腾讯分析会报错？
错误信息如下：
ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: bad indentation of a mapping entry at line 319, column 2:
     tencent_analytics: XXXXXXXX
     ^
    at generateError (/Users/MAC/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/MAC/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/Users/MAC/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1074:7)
    at composeNode (/Users/MAC/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/Users/MAC/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/Users/MAC/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at Object.load (/Users/MAC/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Hexo.yamlHelper (/Users/MAC/hexo/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/Users/MAC/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/MAC/hexo/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/MAC/hexo/node_modules/hexo/lib/hexo/render.js:61:21
    at tryCatcher (/Users/MAC/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/MAC/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/MAC/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/MAC/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/MAC/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/MAC/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/MAC/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/MAC/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by cissoid** [comment]
@tc9011 看错误信息像是这一行之前的配置有缩进问题.

**Comment by tc9011** [comment]
iissnan：


您好，谢谢指导，这个问题已经解决了，确实是缩紧问题。



我还有2个问题向您请教：


1、为什么多说评论本地调试博客的时候出现了，推送到github后，用网址打开就不可以了呢？这个问题至今没解决～


2、腾讯统计为什么不能显示，不蒜子倒是可以显示。


博客源码在https://github.com/tc9011/BlogBackUp;


如能帮忙看一下，不胜感激。


谢谢！


汤诚


在2016年11月02日 17:12，cissoid 写道:

@tc9011 看错误信息像是这一行之前的配置有缩进问题.

**Pull request merged**
