### PR TITLE
Add comment icon

### PR DESCRIPTION
**Pull request by geekrainy**

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@geekrainy what is gentie? Can u give basic link and some description on it?

**Comment by geekrainy** [comment]
@ivan-nginx https://gentie.163.com/
It's a comment plugin. : )

**Comment by ivan-nginx** [comment]
From this pull Next support 4 comments system. :+1: 

- Duoshuo
- Disqus
- Hypercomments
- Gentie

**Comment by iissnan** [comment]
Thanks. :+1:

**Comment by ivan-nginx** [comment]
@geekrainy there is Netease code in #1543. Is that need thing?

**Comment by geekrainy** [comment]
@ivan-nginx #1543 It provides the same code. Do not need merge.

**Pull request merged**
